runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /javascript
  static_dir: javascript
- url: /stylesheets
  static_dir: stylesheets
- url: /img
  static_dir: img
- url: /.*
  script: main.app

# handlers:
# - url: /.*
#   script: main.app


libraries:
- name: jinja2
  version: latest